### ISSUE TITLE
Login credentials are not working

### ISSUE THREAD

**Issue by felipegtx** [blinktrade/algorithm-trading#4]
![image](https://user-images.githubusercontent.com/1022404/33497912-bc038f6c-d6b6-11e7-9bce-ecc04b5b77c8.png)

**Comment by cesardeazevedo** [comment]
Once it's open, always someone change the admin password, so we can't control it, sorry about that, can you try with `foxbit`/`abc12345` instead?

**Comment by felipegtx** [comment]
@cesardeazevedo Still no good. 
Maybe add an `if` there to check for those credentials and keep it from changing the password?

**Comment by cesardeazevedo** [comment]
You need to click on admin link on the footer first, before trying to logging as admin.

**Comment by felipegtx** [comment]
Is the server down right now?

**Comment by cesardeazevedo** [comment]
@felipegtx Yes indeed, our testnet disk were full, it's working fine now.
